#!/bin/bash

. ./bootstrap

SDKPATH="`xcrun --show-sdk-path`"

# Build and copy OpenSCTokenApp
xcodebuild -sdk ${SDKPATH} -target OpenSCTokenApp -configuration Debug -project OpenSCTokenApp.xcodeproj install DSTROOT=${BUILDPATH}

# Add link to Applications
if ! test -e "${BUILDPATH}/Applications/Utilities/Utilities"; then
	ln -s "/Applications/Utilities" "${BUILDPATH}/Applications/Utilities/Utilities"
fi

   name="$(defaults read ${BUILDPATH}/Applications/Utilities/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/Info CFBundleName)"
  title="$(defaults read ${BUILDPATH}/Applications/Utilities/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/Info CFBundleDisplayName)"
version="$(defaults read ${BUILDPATH}/Applications/Utilities/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/Info CFBundleShortVersionString)"
 opensc="$(cat OpenSC/win32/winconfig.h | perl -pe 'if(($v)=/([0-9]+([.][0-9]+)+)/){print"$v\n";exit}$_=""')"

# Create OpenSCToken.pkg (package)
pkgbuild --root ${BUILDPATH} --identifier org.opensc-project.mac.opensctoken --version 1.1.1 --install-location /Applications OpenSCToken.pkg

# Create .dmg
rm -f $name.dmg
i=0
while ! hdiutil create -srcfolder "${BUILDPATH}/Applications/Utilities/" -volname "$title $version (OpenSC $opensc)" $name.dmg
do
	i=$[$i+1]
	if [ $i -gt 2 ]
	then
		exit 1
	fi
done
